import { Question, AnswerOption, PersonalityTypeSlug } from '../../shared/types';

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    question_text: 'When faced with a new challenge, what\'s your first instinct?',
    question_number: 1,
    category: 'approach-to-challenges',
    is_active: true,
  },
  {
    id: 'q2',
    question_text: 'How do you prefer to spend your free time?',
    question_number: 2,
    category: 'leisure-preferences',
    is_active: true,
  },
  {
    id: 'q3',
    question_text: 'In a group project, what role do you naturally take?',
    question_number: 3,
    category: 'social-dynamics',
    is_active: true,
  },
  {
    id: 'q4',
    question_text: 'When making important decisions, you rely mostly on:',
    question_number: 4,
    category: 'decision-making',
    is_active: true,
  },
  {
    id: 'q5',
    question_text: 'How do you handle disagreements with others?',
    question_number: 5,
    category: 'conflict-resolution',
    is_active: true,
  },
  {
    id: 'q6',
    question_text: 'What motivates you most in life?',
    question_number: 6,
    category: 'motivation',
    is_active: true,
  },
  {
    id: 'q7',
    question_text: 'When meeting new people, you typically:',
    question_number: 7,
    category: 'social-interaction',
    is_active: true,
  },
  {
    id: 'q8',
    question_text: 'How do you deal with unexpected changes?',
    question_number: 8,
    category: 'adaptability',
    is_active: true,
  },
  {
    id: 'q9',
    question_text: 'What type of environment do you thrive in?',
    question_number: 9,
    category: 'work-environment',
    is_active: true,
  },
  {
    id: 'q10',
    question_text: 'When you have free time, you prefer to:',
    question_number: 10,
    category: 'leisure-activities',
    is_active: true,
  },
];

export const ANSWER_OPTIONS: AnswerOption[] = [
  // Question 1
  {
    id: 'q1a1',
    question_id: 'q1',
    option_text: 'Dive right in and figure it out as I go',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 2,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 8,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 6,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 1,
      [PersonalityTypeSlug.NATURAL_LEADER]: 7,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 3,
    },
    is_active: true,
  },
  {
    id: 'q1a2',
    question_id: 'q1',
    option_text: 'Research and plan carefully before acting',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 2,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 10,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 4,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 5,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 8,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 7,
    },
    is_active: true,
  },
  {
    id: 'q1a3',
    question_id: 'q1',
    option_text: 'Brainstorm creative solutions with others',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 6,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 4,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 10,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 9,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 3,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 8,
    },
    is_active: true,
  },
  {
    id: 'q1a4',
    question_id: 'q1',
    option_text: 'Observe the situation and reflect on the best approach',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 1,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 7,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 2,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 4,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 6,
    },
    is_active: true,
  },
  // Question 2
  {
    id: 'q2a1',
    question_id: 'q2',
    option_text: 'Trying new activities and adventures',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 3,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 8,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 7,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 2,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 4,
    },
    is_active: true,
  },
  {
    id: 'q2a2',
    question_id: 'q2',
    option_text: 'Reading, learning, or researching',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 3,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 10,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 6,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 9,
      [PersonalityTypeSlug.NATURAL_LEADER]: 7,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 5,
    },
    is_active: true,
  },
  {
    id: 'q2a3',
    question_id: 'q2',
    option_text: 'Creating art, music, or other creative projects',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 5,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 2,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 10,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 6,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 7,
      [PersonalityTypeSlug.NATURAL_LEADER]: 3,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 4,
    },
    is_active: true,
  },
  {
    id: 'q2a4',
    question_id: 'q2',
    option_text: 'Spending time with friends and family',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 6,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 4,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 10,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 2,
      [PersonalityTypeSlug.NATURAL_LEADER]: 7,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 9,
    },
    is_active: true,
  },
  // Question 3
  {
    id: 'q3a1',
    question_id: 'q3',
    option_text: 'Take the lead and organize the team',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 7,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 3,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 6,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 1,
      [PersonalityTypeSlug.NATURAL_LEADER]: 10,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 4,
    },
    is_active: true,
  },
  {
    id: 'q3a2',
    question_id: 'q3',
    option_text: 'Support others and help mediate',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 3,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 6,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 4,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 8,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 2,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 10,
    },
    is_active: true,
  },
  {
    id: 'q3a3',
    question_id: 'q3',
    option_text: 'Contribute creative ideas and solutions',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 6,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 3,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 10,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 7,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 4,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 6,
    },
    is_active: true,
  },
  {
    id: 'q3a4',
    question_id: 'q3',
    option_text: 'Do my part independently and efficiently',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 5,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 8,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 4,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 3,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 5,
    },
    is_active: true,
  },
  // Question 4
  {
    id: 'q4a1',
    question_id: 'q4',
    option_text: 'Gut feeling and intuition',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 2,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 9,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 5,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 4,
      [PersonalityTypeSlug.NATURAL_LEADER]: 7,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 6,
    },
    is_active: true,
  },
  {
    id: 'q4a2',
    question_id: 'q4',
    option_text: 'Facts, data, and logical analysis',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 2,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 10,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 3,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 9,
      [PersonalityTypeSlug.NATURAL_LEADER]: 8,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 5,
    },
    is_active: true,
  },
  {
    id: 'q4a3',
    question_id: 'q4',
    option_text: 'Input from trusted friends and family',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 4,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 10,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 3,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 9,
    },
    is_active: true,
  },
  {
    id: 'q4a4',
    question_id: 'q4',
    option_text: 'What feels right morally and ethically',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 5,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 7,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 6,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 7,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 8,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 10,
    },
    is_active: true,
  },
  // Question 5
  {
    id: 'q5a1',
    question_id: 'q5',
    option_text: 'Address it directly and work through it',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 9,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 7,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 3,
      [PersonalityTypeSlug.NATURAL_LEADER]: 10,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 6,
    },
    is_active: true,
  },
  {
    id: 'q5a2',
    question_id: 'q5',
    option_text: 'Try to mediate and find common ground',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 4,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 6,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 8,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 4,
      [PersonalityTypeSlug.NATURAL_LEADER]: 7,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 10,
    },
    is_active: true,
  },
  {
    id: 'q5a3',
    question_id: 'q5',
    option_text: 'Take time to reflect before responding',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 2,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 8,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 6,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 3,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 7,
    },
    is_active: true,
  },
  {
    id: 'q5a4',
    question_id: 'q5',
    option_text: 'Avoid conflict and maintain harmony',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 1,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 4,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 3,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 6,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 5,
      [PersonalityTypeSlug.NATURAL_LEADER]: 3,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 10,
    },
    is_active: true,
  },
  // Question 6
  {
    id: 'q6a1',
    question_id: 'q6',
    option_text: 'Achievement and success',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 8,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 6,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 3,
      [PersonalityTypeSlug.NATURAL_LEADER]: 10,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 2,
    },
    is_active: true,
  },
  {
    id: 'q6a2',
    question_id: 'q6',
    option_text: 'Learning and personal growth',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 7,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 10,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 9,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 5,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 8,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 4,
    },
    is_active: true,
  },
  {
    id: 'q6a3',
    question_id: 'q6',
    option_text: 'Helping others and making a difference',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 5,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 7,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 6,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 10,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 4,
      [PersonalityTypeSlug.NATURAL_LEADER]: 8,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 10,
    },
    is_active: true,
  },
  {
    id: 'q6a4',
    question_id: 'q6',
    option_text: 'Freedom and new experiences',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 2,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 8,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 6,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 5,
      [PersonalityTypeSlug.NATURAL_LEADER]: 4,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 3,
    },
    is_active: true,
  },
  // Question 7
  {
    id: 'q7a1',
    question_id: 'q7',
    option_text: 'Introduce myself and start conversations',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 9,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 4,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 7,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 10,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 1,
      [PersonalityTypeSlug.NATURAL_LEADER]: 8,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 5,
    },
    is_active: true,
  },
  {
    id: 'q7a2',
    question_id: 'q7',
    option_text: 'Observe quietly before engaging',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 2,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 6,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 3,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 4,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 7,
    },
    is_active: true,
  },
  {
    id: 'q7a3',
    question_id: 'q7',
    option_text: 'Look for familiar faces and stick with them',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 4,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 4,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 8,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 6,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 9,
    },
    is_active: true,
  },
  {
    id: 'q7a4',
    question_id: 'q7',
    option_text: 'Wait for others to approach me',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 1,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 3,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 9,
      [PersonalityTypeSlug.NATURAL_LEADER]: 3,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 8,
    },
    is_active: true,
  },
  // Question 8
  {
    id: 'q8a1',
    question_id: 'q8',
    option_text: 'Embrace them as exciting opportunities',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 2,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 9,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 7,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 2,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 4,
    },
    is_active: true,
  },
  {
    id: 'q8a2',
    question_id: 'q8',
    option_text: 'Feel anxious but adapt eventually',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 5,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 6,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 7,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 8,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 7,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 9,
    },
    is_active: true,
  },
  {
    id: 'q8a3',
    question_id: 'q8',
    option_text: 'Need time to process and adjust',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 3,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 8,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 5,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 7,
    },
    is_active: true,
  },
  {
    id: 'q8a4',
    question_id: 'q8',
    option_text: 'Prefer stability and resist change',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 1,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 9,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 2,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 3,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 8,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 7,
    },
    is_active: true,
  },
  // Question 9
  {
    id: 'q9a1',
    question_id: 'q9',
    option_text: 'Fast-paced and dynamic',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 2,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 8,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 7,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 1,
      [PersonalityTypeSlug.NATURAL_LEADER]: 8,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 3,
    },
    is_active: true,
  },
  {
    id: 'q9a2',
    question_id: 'q9',
    option_text: 'Quiet and focused',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 2,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 8,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 7,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 3,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 5,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 6,
    },
    is_active: true,
  },
  {
    id: 'q9a3',
    question_id: 'q9',
    option_text: 'Collaborative and social',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 6,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 7,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 10,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 2,
      [PersonalityTypeSlug.NATURAL_LEADER]: 8,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 9,
    },
    is_active: true,
  },
  {
    id: 'q9a4',
    question_id: 'q9',
    option_text: 'Structured and predictable',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 1,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 10,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 3,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 4,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 7,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 8,
    },
    is_active: true,
  },
  // Question 10
  {
    id: 'q10a1',
    question_id: 'q10',
    option_text: 'Explore new places and try new things',
    option_order: 1,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 10,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 3,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 8,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 7,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 2,
      [PersonalityTypeSlug.NATURAL_LEADER]: 6,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 4,
    },
    is_active: true,
  },
  {
    id: 'q10a2',
    question_id: 'q10',
    option_text: 'Relax and recharge alone',
    option_order: 2,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 3,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 6,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 7,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 2,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 10,
      [PersonalityTypeSlug.NATURAL_LEADER]: 4,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 7,
    },
    is_active: true,
  },
  {
    id: 'q10a3',
    question_id: 'q10',
    option_text: 'Engage in creative hobbies',
    option_order: 3,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 5,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 3,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 10,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 5,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 8,
      [PersonalityTypeSlug.NATURAL_LEADER]: 3,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 6,
    },
    is_active: true,
  },
  {
    id: 'q10a4',
    question_id: 'q10',
    option_text: 'Spend quality time with loved ones',
    option_order: 4,
    scoring_weights: {
      [PersonalityTypeSlug.BOLD_EXPLORER]: 6,
      [PersonalityTypeSlug.WISE_GUARDIAN]: 5,
      [PersonalityTypeSlug.CREATIVE_SPARK]: 4,
      [PersonalityTypeSlug.SOCIAL_BUTTERFLY]: 10,
      [PersonalityTypeSlug.QUIET_OBSERVER]: 3,
      [PersonalityTypeSlug.NATURAL_LEADER]: 7,
      [PersonalityTypeSlug.GENTLE_PEACEMAKER]: 10,
    },
    is_active: true,
  },
];

export const getQuestionWithOptions = (questionId: string) => {
  const question = QUESTIONS.find(q => q.id === questionId);
  const options = ANSWER_OPTIONS.filter(ao => ao.question_id === questionId).sort((a, b) => a.option_order - b.option_order);
  return question ? { ...question, answer_options: options } : null;
};

export const getQuestionsWithOptions = () => {
  return QUESTIONS
    .filter(q => q.is_active)
    .sort((a, b) => a.question_number - b.question_number)
    .map(q => getQuestionWithOptions(q.id)!);
};
